import { useParams, useNavigate } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import {
  ArrowLeft,
  CreditCard,
  DollarSign,
  Calendar,
  FileText,
  Printer,
  Receipt,
} from 'lucide-react'
import { receiptApi } from '../../services/api'
import { formatCurrency, formatDate, cn } from '../../lib/utils'
import { Button } from '../../components/ui'
import { TbUserSquareRounded } from 'react-icons/tb'

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.05 },
  },
}

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 },
}

const methodLabels: Record<string, string> = {
  cash: 'Cash',
  bank_transfer: 'Bank Transfer',
  ecocash: 'EcoCash',
  card: 'Card',
  cheque: 'Cheque',
}

interface StatCardProps {
  title: string
  value: string | number
  subtitle?: string
  icon: React.ElementType
  color: 'blue' | 'green' | 'purple' | 'orange'
  isLoading?: boolean
}

const colorConfig = {
  blue: { bg: 'bg-blue-50', icon: 'bg-blue-500', text: 'text-blue-600' },
  green: { bg: 'bg-emerald-50', icon: 'bg-emerald-500', text: 'text-emerald-600' },
  purple: { bg: 'bg-purple-50', icon: 'bg-purple-500', text: 'text-purple-600' },
  orange: { bg: 'bg-orange-50', icon: 'bg-orange-500', text: 'text-orange-600' },
}

function StatCard({ title, value, subtitle, icon: Icon, color, isLoading }: StatCardProps) {
  const colors = colorConfig[color]
  return (
    <motion.div
      variants={item}
      className="bg-white rounded-xl border border-gray-200 p-4 md:p-6 hover:shadow-lg hover:border-gray-300 transition-all duration-300"
    >
      <div className="flex items-start justify-between">
        <div className={cn('p-2 md:p-3 rounded-xl', colors.bg)}>
          <div className={cn('p-1.5 md:p-2 rounded-lg', colors.icon)}>
            <Icon className="w-4 h-4 md:w-5 md:h-5 text-white" />
          </div>
        </div>
      </div>
      <div className="mt-3 md:mt-4">
        {isLoading ? (
          <div className="h-8 md:h-9 w-20 md:w-24 bg-gray-200 rounded animate-pulse" />
        ) : (
          <h3 className="text-2xl md:text-3xl font-bold text-gray-900 tabular-nums">{value}</h3>
        )}
        <p className="text-xs md:text-sm text-gray-500 mt-1">{title}</p>
        {isLoading ? (
          <div className="h-3 md:h-4 w-16 md:w-20 bg-gray-200 rounded animate-pulse mt-1" />
        ) : subtitle ? (
          <p className="text-xs text-gray-400 mt-1">{subtitle}</p>
        ) : null}
      </div>
    </motion.div>
  )
}

export default function ReceiptDetail() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const receiptId = Number(id)

  const { data: receipt, isLoading } = useQuery({
    queryKey: ['receipt', receiptId],
    queryFn: () => receiptApi.get(receiptId).then((r) => r.data),
    enabled: !!receiptId,
  })

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (!printWindow) return

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Receipt ${receipt?.receipt_number}</title>
        <style>
          body { font-family: -apple-system, sans-serif; padding: 40px; color: #1a1a1a; }
          .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #e5e7eb; }
          .header h1 { font-size: 28px; margin: 0 0 5px; }
          .amount { background: #059669; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
          .amount p { font-size: 32px; font-weight: bold; margin: 5px 0 0; }
          .footer { margin-top: 40px; font-size: 11px; color: #9ca3af; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>RECEIPT</h1>
          <p>${receipt?.receipt_number}</p>
        </div>
        <p><strong>Tenant:</strong> ${receipt?.tenant_name}</p>
        ${receipt?.invoice_number ? `<p><strong>Invoice:</strong> ${receipt.invoice_number}</p>` : ''}
        <p><strong>Date:</strong> ${receipt?.date ? formatDate(receipt.date) : '-'}</p>
        <p><strong>Method:</strong> ${methodLabels[receipt?.payment_method] || receipt?.payment_method}</p>
        ${receipt?.reference ? `<p><strong>Reference:</strong> ${receipt.reference}</p>` : ''}
        <div class="amount">
          <small>AMOUNT RECEIVED</small>
          <p>${formatCurrency(receipt?.amount || 0)}</p>
        </div>
        <div class="footer">Generated by Parameter Real Estate Accounting System</div>
      </body>
      </html>
    `)
    printWindow.document.close()
    printWindow.onload = () => { printWindow.focus(); printWindow.print(); printWindow.close() }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between"
      >
        <div className="flex items-center gap-4">
          <button onClick={() => navigate('/dashboard/receipts')} className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
            <ArrowLeft className="w-5 h-5 text-gray-600" />
          </button>
          <div className="flex items-center gap-3">
            {isLoading ? (
              <div className="h-8 w-48 bg-gray-200 rounded animate-pulse" />
            ) : (
              <>
                <h1 className="text-xl md:text-2xl font-bold text-gray-900">Receipt {receipt?.receipt_number}</h1>
                <span className="px-2.5 py-1 rounded-full text-xs font-medium bg-emerald-50 text-emerald-600">Received</span>
              </>
            )}
          </div>
        </div>
        <Button variant="outline" onClick={handlePrint} className="gap-2">
          <Printer className="w-4 h-4" />
          Print
        </Button>
      </motion.div>

      {/* Profile Info Bar */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.05 }}
        className="bg-white rounded-xl border border-gray-200 p-4 md:p-6"
      >
        {isLoading ? (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="space-y-2 animate-pulse">
                <div className="h-3 w-16 bg-gray-200 rounded" />
                <div className="h-4 w-32 bg-gray-200 rounded" />
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {/* Tenant */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Tenant</p>
              <button
                onClick={() => receipt?.tenant && navigate(`/dashboard/tenants/${receipt.tenant}`)}
                className="flex items-center gap-2 text-sm text-primary-600 hover:text-primary-700 transition-colors"
              >
                <TbUserSquareRounded className="w-3.5 h-3.5" />
                <span>{receipt?.tenant_name}</span>
              </button>
            </div>

            {/* Invoice */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Invoice</p>
              {receipt?.invoice_number ? (
                <button
                  onClick={() => receipt?.invoice && navigate(`/dashboard/invoices/${receipt.invoice}`)}
                  className="flex items-center gap-2 text-sm text-primary-600 hover:text-primary-700 transition-colors"
                >
                  <Receipt className="w-3.5 h-3.5" />
                  <span>{receipt.invoice_number}</span>
                </button>
              ) : (
                <p className="text-sm text-gray-400">No linked invoice</p>
              )}
            </div>

            {/* Payment */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Payment</p>
              <div className="space-y-1.5">
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <DollarSign className="w-3.5 h-3.5 text-gray-400" />
                  <span className="font-semibold">{formatCurrency(receipt?.amount || 0)}</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <CreditCard className="w-3.5 h-3.5 text-gray-400" />
                  <span>{methodLabels[receipt?.payment_method] || receipt?.payment_method}</span>
                </div>
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <Calendar className="w-3.5 h-3.5 text-gray-400" />
                  <span>{receipt?.date ? formatDate(receipt.date) : '-'}</span>
                </div>
                {receipt?.reference && (
                  <div className="text-xs text-gray-500 font-mono">{receipt.reference}</div>
                )}
              </div>
            </div>

            {/* Accounting */}
            <div className="space-y-2">
              <p className="text-xs font-medium text-gray-400 uppercase tracking-wider">Accounting</p>
              {receipt?.journal_number ? (
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <FileText className="w-3.5 h-3.5 text-gray-400" />
                  <span>{receipt.journal_number}</span>
                </div>
              ) : (
                <p className="text-sm text-gray-400">Not posted to GL</p>
              )}
            </div>
          </div>
        )}
      </motion.div>

      {/* KPI Cards */}
      <motion.div variants={container} initial="hidden" animate="show" className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <StatCard title="Amount" value={formatCurrency(receipt?.amount || 0)} icon={DollarSign} color="blue" isLoading={isLoading} />
        <StatCard title="Payment Method" value={methodLabels[receipt?.payment_method] || receipt?.payment_method || '-'} icon={CreditCard} color="green" isLoading={isLoading} />
        <StatCard title="Date" value={receipt?.date ? formatDate(receipt.date) : '-'} icon={Calendar} color="purple" isLoading={isLoading} />
        <StatCard title="Journal Entry" value={receipt?.journal_number || 'N/A'} icon={FileText} color="orange" isLoading={isLoading} />
      </motion.div>

      {/* Payment Details Card */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="bg-white rounded-xl border border-gray-200 p-6"
      >
        <h3 className="text-lg font-semibold text-gray-900 mb-4">Payment Details</h3>
        {isLoading ? (
          <div className="space-y-3 animate-pulse">
            <div className="h-4 w-3/4 bg-gray-200 rounded" />
            <div className="h-4 w-1/2 bg-gray-200 rounded" />
          </div>
        ) : (
          <div className="space-y-4">
            {receipt?.description && (
              <div>
                <p className="text-sm text-gray-500 mb-1">Description</p>
                <p className="text-sm text-gray-700">{receipt.description}</p>
              </div>
            )}

            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 pt-4 border-t border-gray-100">
              <div>
                <p className="text-xs text-gray-500">Receipt Number</p>
                <p className="text-sm font-medium text-gray-900">{receipt?.receipt_number}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Tenant</p>
                <p className="text-sm font-medium text-gray-900">{receipt?.tenant_name}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Amount</p>
                <p className="text-sm font-medium text-emerald-600">{formatCurrency(receipt?.amount || 0)}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Payment Method</p>
                <p className="text-sm font-medium text-gray-900">{methodLabels[receipt?.payment_method] || receipt?.payment_method}</p>
              </div>
              <div>
                <p className="text-xs text-gray-500">Date</p>
                <p className="text-sm font-medium text-gray-900">{receipt?.date ? formatDate(receipt.date) : '-'}</p>
              </div>
              {receipt?.reference && (
                <div>
                  <p className="text-xs text-gray-500">Reference</p>
                  <p className="text-sm font-medium text-gray-900 font-mono">{receipt.reference}</p>
                </div>
              )}
            </div>
          </div>
        )}
      </motion.div>

      {/* Related Invoice Link */}
      {receipt?.invoice_number && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25 }}
          className="bg-white rounded-xl border border-gray-200 p-6"
        >
          <h3 className="text-lg font-semibold text-gray-900 mb-3">Related Invoice</h3>
          <button
            onClick={() => receipt?.invoice && navigate(`/dashboard/invoices/${receipt.invoice}`)}
            className="flex items-center gap-3 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors w-full text-left"
          >
            <div className="p-2 bg-primary-50 rounded-lg">
              <Receipt className="w-5 h-5 text-primary-600" />
            </div>
            <div>
              <p className="font-semibold text-gray-900">{receipt.invoice_number}</p>
              <p className="text-sm text-gray-500">View invoice details</p>
            </div>
          </button>
        </motion.div>
      )}
    </div>
  )
}
