# Generated by Django 4.2.27 on 2026-01-24 15:10

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], default='bank', max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold (ZiG)'), ('ZWL', 'Zimbabwe Dollar')], default='USD', max_length=3)),
                ('book_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_reconciled_date', models.DateField(blank=True, null=True)),
                ('last_reconciled_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_subtype',
            field=models.CharField(choices=[('cash', 'Cash & Bank'), ('accounts_receivable', 'Accounts Receivable'), ('prepaid', 'Prepaid Expenses'), ('fixed_asset', 'Fixed Assets'), ('accounts_payable', 'Accounts Payable'), ('vat_payable', 'VAT Payable'), ('tenant_deposits', 'Tenant Deposits'), ('retained_earnings', 'Retained Earnings'), ('capital', 'Capital'), ('rental_income', 'Rental Income'), ('levy_income', 'Levy Income'), ('special_levy_income', 'Special Levy Income'), ('rates_income', 'Rates Income'), ('parking_income', 'Parking Income'), ('vat_income', 'VAT Income'), ('commission_income', 'Commission Income'), ('other_income', 'Other Income'), ('operating_expense', 'Operating Expenses'), ('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('custom_expense', 'Custom Expense')], max_length=30),
        ),
        migrations.CreateModel(
            name='JournalReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocated_from', to='accounting.chartofaccount')),
                ('new_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_to', to='accounting.journalentry')),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocations_from', to='accounting.journalentry')),
                ('reallocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocated_to', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name': 'Journal Reallocation',
                'verbose_name_plural': 'Journal Reallocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_commissionable', models.BooleanField(default=True)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('is_vatable', models.BooleanField(default=False)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gl_account', models.ForeignKey(limit_choices_to={'account_type': 'revenue'}, on_delete=django.db.models.deletion.PROTECT, related_name='income_types', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name': 'Income Type',
                'verbose_name_plural': 'Income Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_deductible', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which approval is required', max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gl_account', models.ForeignKey(limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('adjusted_book_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('outstanding_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('outstanding_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='gl_account',
            field=models.ForeignKey(limit_choices_to={'account_subtype': 'cash'}, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.chartofaccount'),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Deposit)'), ('debit', 'Debit (Withdrawal)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled'), ('disputed', 'Disputed')], default='unreconciled', max_length=20)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('ai_match_confidence', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_match_suggestion', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount')),
                ('matched_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='accounting.journal')),
                ('matched_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='billing.receipt')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['bank_account', 'status'], name='accounting__bank_ac_35a6d6_idx'), models.Index(fields=['transaction_date'], name='accounting__transac_75d7a8_idx')],
            },
        ),
    ]
