# Generated by Django 5.0.14 on 2026-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount_alter_chartofaccount_account_subtype_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__3d844c_idx'),
        ),
    ]
