# Generated by Django 5.0.14 on 2026-02-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='banktransaction',
            name='accounting_btx_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='accounting_coa_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='accounting_coa_type_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='accounting_jrn_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='accounting_jrn_type_idx',
        ),
    ]
