# Generated by Django 5.0.14 on 2026-02-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_search_filter_indexes'),
        ('billing', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=10)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='accounting.generalledger')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='billing.receipt')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.bankreconciliation')),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['reconciliation', 'is_reconciled'], name='accounting__reconci_4280d2_idx')],
            },
        ),
    ]
