# Generated by Django 5.0.14 on 2026-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_reconciliationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incometype',
            name='management_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('levy', 'Levy'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
