# Generated by Django 5.0.14 on 2026-03-07 07:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_incometype_is_system_incometype_management_type'),
        ('masterfile', '0011_landlord_portal_user_leaseagreement_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('account_holder', 'Account Holder')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_account', to='masterfile.landlord')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_account', to='masterfile.rentaltenant')),
            ],
            options={
                'verbose_name': 'Subsidiary Account',
                'verbose_name_plural': 'Subsidiary Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubsidiaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateField()),
                ('contra_account', models.CharField(help_text='Code of the other side of the entry (e.g., 2300/010, 4000/001, LD/3000)', max_length=20)),
                ('reference', models.CharField(help_text='Document reference (INV-xxxxxx, RCT-xxxxxx, CMA-xxxxxx)', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.subsidiaryaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_transactions', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Subsidiary Transaction',
                'verbose_name_plural': 'Subsidiary Transactions',
                'ordering': ['transaction_number'],
            },
        ),
        migrations.AddIndex(
            model_name='subsidiaryaccount',
            index=models.Index(fields=['entity_type', 'is_active'], name='accounting__entity__59f4af_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidiarytransaction',
            index=models.Index(fields=['account', 'date'], name='accounting__account_986990_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidiarytransaction',
            index=models.Index(fields=['date'], name='accounting__date_fa17a4_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidiarytransaction',
            index=models.Index(fields=['reference'], name='accounting__referen_aaed48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subsidiarytransaction',
            unique_together={('account', 'transaction_number')},
        ),
    ]
