# Generated by Django 5.0.14 on 2026-03-25 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_add_subsidiary_ledger'),
        ('masterfile', '0012_make_lease_unit_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiaryaccount',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='subsidiaryaccount',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_accounts', to='masterfile.landlord'),
        ),
    ]
