# Generated by Django 5.0.14 on 2026-04-01 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_subsidiary_category'),
        ('billing', '0009_expense_expense_category_expense_income_type'),
        ('masterfile', '0012_make_lease_unit_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_subtype',
            field=models.CharField(choices=[('cash', 'Cash & Bank'), ('accounts_receivable', 'Accounts Receivable'), ('prepaid', 'Prepaid Expenses'), ('fixed_asset', 'Fixed Assets'), ('accounts_payable', 'Accounts Payable'), ('vat_payable', 'VAT Payable'), ('tenant_deposits', 'Tenant Deposits'), ('retained_earnings', 'Retained Earnings'), ('capital', 'Capital'), ('rental_income', 'Rental Income'), ('levy_income', 'Levy Income'), ('special_levy_income', 'Special Levy Income'), ('rates_income', 'Rates Income'), ('parking_income', 'Parking Income'), ('vat_income', 'VAT Income'), ('commission_income', 'Commission Income'), ('other_income', 'Other Income'), ('operating_expense', 'Operating Expenses'), ('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('custom_expense', 'Custom Expense'), ('depreciation', 'Depreciation'), ('accrued_liabilities', 'Accrued Liabilities'), ('accumulated_depreciation', 'Accumulated Depreciation')], max_length=30),
        ),
        migrations.CreateModel(
            name='AccruedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('expense_class', models.CharField(choices=[('clearable', 'Clearable'), ('non_clearable', 'Non-Clearable')], max_length=20)),
                ('funding_category', models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('general', 'General')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('custom_description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cleared', 'Cleared')], default='draft', max_length=20)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accrual_sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrued_expenses', to='accounting.subsidiaryaccount')),
                ('cleared_by_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_accruals', to='billing.expense')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrued_expenses', to='accounting.chartofaccount')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journal')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrued_expenses', to='masterfile.landlord')),
                ('landlord_sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrued_landlord_expenses', to='accounting.subsidiaryaccount')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrued_payables', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('general', 'General')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('custom_description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bs_movement_credits', to='accounting.chartofaccount')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bs_movement_debits', to='accounting.chartofaccount')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journal')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bs_movements', to='masterfile.landlord')),
                ('landlord_sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bs_movements', to='accounting.subsidiaryaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
