# Generated by Django 5.0.14 on 2026-04-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_add_accrued_expense_and_bs_movement'),
        ('masterfile', '0012_make_lease_unit_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('debit', 'Debit (introduce asset/receivable)'), ('credit', 'Credit (introduce liability/prepayment)')], max_length=10)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('general', 'General')], max_length=20)),
                ('description', models.CharField(default='Opening balance', max_length=500)),
                ('custom_description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journal')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='masterfile.landlord')),
                ('landlord_sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances', to='accounting.subsidiaryaccount')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='accounting.chartofaccount')),
                ('tenant_sub_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_tenant', to='accounting.subsidiaryaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
