# Generated by Django 5.0.14 on 2026-04-04 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_add_opening_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='consolidation_marker',
            field=models.CharField(blank=True, default='', help_text="'C' if this is a consolidated result", max_length=1),
        ),
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='is_consolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='overwritten_description',
            field=models.CharField(blank=True, help_text='New description if narration was overwritten', max_length=500),
        ),
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='reversed_transaction',
            field=models.ForeignKey(blank=True, help_text='Points to the original transaction being reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.subsidiarytransaction'),
        ),
        migrations.CreateModel(
            name='TransactionConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to='accounting.subsidiaryaccount')),
                ('consolidated_entry', models.OneToOneField(blank=True, help_text='The visible merged transaction (created by consolidation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consolidation', to='accounting.subsidiarytransaction')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_transactions', models.ManyToManyField(help_text='Original transactions that were merged', related_name='consolidated_into', to='accounting.subsidiarytransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
