# Generated by Django 5.0.14 on 2026-05-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_subsidiarytransaction_consolidation_marker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='default_description',
            field=models.CharField(blank=True, help_text='Auto-fills the description field on expense creation', max_length=255),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='funding_category',
            field=models.CharField(choices=[('rent', 'Rent'), ('maintenance', 'Maintenance'), ('rates', 'Rates'), ('parking', 'Parking'), ('vat', 'VAT')], default='rent', help_text='Landlord sub-account this expense is funded from', max_length=20),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='gl_account_zwg',
            field=models.ForeignKey(blank=True, help_text='ZWG GL account (defaults to gl_account if not set)', limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories_zwg', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='accruedexpense',
            name='funding_category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='balancesheetmovement',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='gl_account',
            field=models.ForeignKey(help_text='USD GL account for this expense type', limit_choices_to={'account_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='openingbalance',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit'), ('general', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subsidiaryaccount',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
    ]
