# Generated by Django 5.0.14 on 2026-05-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_expensecategory_default_description_and_more'),
        ('masterfile', '0014_property_income_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional creditor/supplier this OB is owed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balances', to='masterfile.supplier'),
        ),
    ]
