# Generated by Django 5.0.14 on 2026-06-26 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_chartofaccount_balance_sheet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='subsidiary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.subsidiaryaccount'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.chartofaccount'),
        ),
    ]
