# Generated by Django 5.0.14 on 2026-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_journalentry_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_subtype',
            field=models.CharField(choices=[('cash', 'Cash & Bank'), ('accounts_receivable', 'Accounts Receivable'), ('prepaid', 'Prepaid Expenses'), ('fixed_asset', 'Fixed Assets'), ('movable_asset', 'Movable Asset'), ('investment', 'Investments'), ('accounts_payable', 'Accounts Payable'), ('vat_payable', 'VAT Payable'), ('tenant_deposits', 'Tenant Deposits'), ('retained_earnings', 'Retained Earnings'), ('capital', 'Capital'), ('rental_income', 'Rental Income'), ('levy_income', 'Levy Income'), ('special_levy_income', 'Special Levy Income'), ('rates_income', 'Rates Income'), ('parking_income', 'Parking Income'), ('vat_income', 'VAT Income'), ('commission_income', 'Commission Income'), ('other_income', 'Other Income'), ('operating_expense', 'Operating Expenses'), ('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('custom_expense', 'Custom Expense'), ('depreciation', 'Depreciation'), ('accrued_liabilities', 'Accrued Liabilities'), ('accumulated_depreciation', 'Accumulated Depreciation')], max_length=30),
        ),
    ]
