# Generated by Django 5.0.14 on 2026-07-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_chartofaccount_account_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='balance_sheet_category',
            field=models.CharField(blank=True, choices=[('non_current_assets', 'Non-Current Assets'), ('current_assets', 'Current Assets'), ('accounts_receivable', 'Accounts Receivables'), ('investments', 'Investments'), ('funds_held_in_trust', 'Funds Held in Trust'), ('lessees_arrears', 'Lessees Arrears'), ('prepayments', 'Prepayments'), ('other_current_assets', 'Other Current Assets'), ('funds_owed_by_trust', 'Funds Owed by Trust'), ('lessees_prepayments', 'Lessees Prepayments'), ('accruals', 'Accruals'), ('other_current_liabilities', 'Other Current Liabilities')], default='', max_length=40),
        ),
    ]
