# Generated by Django 5.0.14 on 2026-07-17 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_chartofaccount_balance_sheet_category'),
        ('masterfile', '0015_supplier_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiaryaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_accounts', to='masterfile.rentaltenant'),
        ),
    ]
