# Generated by Django 5.0.14 on 2026-07-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_subsidiaryaccount_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='account_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='account_subclass',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='hierarchy_type',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
