# Generated by Django 5.0.14 on 2026-07-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_hierarchical_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='extension_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extension_entries', to='accounting.chartofaccount'),
        ),
    ]
