# Generated by Django 5.0.14 on 2026-07-28 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_journal_extension_account'),
        ('billing', '0016_paymentreminder'),
        ('masterfile', '0018_currency_conversions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=30)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference_from', models.CharField(blank=True, default='', max_length=50)),
                ('reference_to', models.CharField(blank=True, default='', max_length=50)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions_out', to='accounting.journal')),
                ('journal_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions_in', to='accounting.journal')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='billing.receipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversions', to='masterfile.rentaltenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='accounting__tenant__1605a5_idx')],
            },
        ),
    ]
