# Generated by Django 5.0.14 on 2026-07-28 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_currency_conversions'),
        ('masterfile', '0018_currency_conversions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrapropertyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_category', models.CharField(max_length=30)),
                ('to_category', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('commission_reversed', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission_charged', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('narration', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_commissions', to='accounting.journal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='accounting.journal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraproperty_transfers', to='masterfile.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intraproperty_transfers', to='masterfile.rentaltenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'created_at'], name='accounting__propert_878f43_idx')],
            },
        ),
    ]
