# Generated by Django 5.0.14 on 2026-08-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_intraproperty_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='transaction_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Global sequential transaction number (chronological trace)', null=True, unique=True),
        ),
    ]
