# Generated by Django 5.0.14 on 2026-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_backfill_transaction_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiaryaccount',
            name='sub_account_number',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='subsidiaryaccount',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
