# Generated by Django 5.0.14 on 2026-08-11 15:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_account_coding_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarytransaction',
            name='currency',
            field=models.CharField(db_index=True, default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='SubsidiaryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='accounting.subsidiaryaccount')),
            ],
            options={
                'verbose_name': 'Subsidiary Balance',
                'verbose_name_plural': 'Subsidiary Balances',
                'indexes': [models.Index(fields=['account', 'currency'], name='accounting__account_d43f8a_idx')],
                'unique_together': {('account', 'currency')},
            },
        ),
    ]
