# Generated by Django 5.0.14 on 2026-08-12 11:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_merge_currency_pockets'),
        ('masterfile', '0020_propertybillingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalanceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=30, unique=True)),
                ('account_type', models.CharField(choices=[('tenant', 'Tenant'), ('account_holder', 'Account Holder')], max_length=20)),
                ('date', models.DateField(help_text='Effective date of the opening balances')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('posted', 'Posted'), ('partially_failed', 'Partially Failed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('posted_journal_ids', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_batches', to='masterfile.property')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening balance import batch',
                'verbose_name_plural': 'Opening balance import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('account_code', models.CharField(blank=True, max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('error', 'Error'), ('posted', 'Posted'), ('skipped', 'Skipped')], default='error', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounting.openingbalanceimportbatch')),
                ('subsidiary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.subsidiaryaccount')),
                ('subsidiary_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.subsidiarytransaction')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterfile.rentaltenant')),
            ],
            options={
                'verbose_name': 'Opening balance import row',
                'verbose_name_plural': 'Opening balance import rows',
                'ordering': ['source_row', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='openingbalanceimportbatch',
            index=models.Index(fields=['property', 'status'], name='accounting__propert_4c0d68_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceimportbatch',
            index=models.Index(fields=['batch_number'], name='accounting__batch_n_1faafe_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalanceimportrow',
            index=models.Index(fields=['batch', 'status'], name='accounting__batch_i_17aa2a_idx'),
        ),
    ]
