# Generated by Django 5.0.14 on 2026-08-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_openingbalanceimportbatch_openingbalanceimportrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingbalance',
            name='corresponding_account',
            field=models.ForeignKey(blank=True, help_text='GL account for the other side of the journal. Blank = 9000.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance_contras', to='accounting.chartofaccount'),
        ),
    ]
