# Generated by Django 5.0.14 on 2026-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_openingbalance_corresponding_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetmovement',
            name='transaction_nature',
            field=models.CharField(choices=[('cash', 'Cash'), ('non_cash', 'Non-Cash')], default='non_cash', max_length=10),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='transaction_nature',
            field=models.CharField(choices=[('cash', 'Cash'), ('non_cash', 'Non-Cash')], default='non_cash', max_length=10),
        ),
    ]
