# Generated by Django 5.0.14 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_balancesheetmovement_transaction_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='reporting_category',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reporting_category',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['reporting_category', 'date'], name='accounting__reporti_6c27c6_idx'),
        ),
    ]
