# Generated by Django 4.2.27 on 2026-01-15 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_masterfile_changes', models.BooleanField(default=True)),
                ('email_invoice_alerts', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('email_lease_alerts', models.BooleanField(default=True)),
                ('email_system_alerts', models.BooleanField(default=True)),
                ('push_masterfile_changes', models.BooleanField(default=True)),
                ('push_invoice_alerts', models.BooleanField(default=True)),
                ('push_payment_received', models.BooleanField(default=True)),
                ('push_lease_alerts', models.BooleanField(default=True)),
                ('push_system_alerts', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='08:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('masterfile_created', 'Masterfile Created'), ('masterfile_updated', 'Masterfile Updated'), ('masterfile_deleted', 'Masterfile Deleted'), ('invoice_created', 'Invoice Created'), ('invoice_overdue', 'Invoice Overdue'), ('invoice_reminder', 'Invoice Reminder'), ('payment_received', 'Payment Received'), ('lease_expiring', 'Lease Expiring'), ('lease_activated', 'Lease Activated'), ('lease_terminated', 'Lease Terminated'), ('system_alert', 'System Alert'), ('user_invited', 'User Invited'), ('user_joined', 'User Joined')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
        migrations.CreateModel(
            name='MasterfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('landlord', 'Landlord'), ('property', 'Property'), ('unit', 'Unit'), ('tenant', 'Tenant'), ('lease', 'Lease Agreement')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(default=dict)),
                ('changed_by_email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterfile_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__5ded6e_idx'), models.Index(fields=['change_type'], name='notificatio_change__d8b20e_idx'), models.Index(fields=['changed_by'], name='notificatio_changed_09d9bc_idx'), models.Index(fields=['created_at'], name='notificatio_created_da4e27_idx')],
            },
        ),
    ]
