# Generated by Django 5.0.14 on 2026-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_late_penalty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_rental_due',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_late_penalty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_rental_due',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('masterfile_created', 'Masterfile Created'), ('masterfile_updated', 'Masterfile Updated'), ('masterfile_deleted', 'Masterfile Deleted'), ('invoice_created', 'Invoice Created'), ('invoice_overdue', 'Invoice Overdue'), ('invoice_reminder', 'Invoice Reminder'), ('payment_received', 'Payment Received'), ('lease_expiring', 'Lease Expiring'), ('lease_activated', 'Lease Activated'), ('lease_terminated', 'Lease Terminated'), ('rental_due', 'Rental Due Reminder'), ('late_penalty', 'Late Payment Penalty'), ('system_alert', 'System Alert'), ('user_invited', 'User Invited'), ('user_joined', 'User Joined')], max_length=30),
        ),
    ]
