# Generated by Django 4.2.27 on 2026-01-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount_alter_chartofaccount_account_subtype_and_more'),
        ('masterfile', '0002_leaseagreement_lease_type_leaseagreement_property_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounting.incometype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='masterfile.property'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account into which payment was received', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.incometype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('rates', 'Rates'), ('parking', 'Parking'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('vat', 'VAT'), ('other', 'Other')], default='rent', max_length=20),
        ),
    ]
