# Generated by Django 5.0.14 on 2026-02-15 13:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_journalentry_accounting__source__3d844c_idx'),
        ('billing', '0002_invoice_income_type_invoice_property_and_more'),
        ('masterfile', '0005_propertymanager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LatePenaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('percentage', 'Percentage of Invoice'), ('flat_fee', 'Flat Fee'), ('both', 'Percentage + Flat Fee')], default='percentage', max_length=20)),
                ('percentage_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Percentage of overdue amount', max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Additional days after due date before penalty applies')),
                ('max_penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum penalty amount (null = no cap)', max_digits=18, null=True)),
                ('max_penalties_per_invoice', models.PositiveIntegerField(default=1, help_text='0 = recurring monthly, 1 = one-time, N = max N penalties')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Late Penalty Configuration',
                'verbose_name_plural': 'Late Penalty Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LatePenaltyExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('excluded_until', models.DateField(blank=True, help_text='Null = permanent exclusion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Late Penalty Exclusion',
                'verbose_name_plural': 'Late Penalty Exclusions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('rates', 'Rates'), ('parking', 'Parking'), ('penalty', 'Late Payment Penalty'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('vat', 'VAT'), ('other', 'Other')], default='rent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'period_start'], name='billing_inv_lease_i_b6288f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant'], name='billing_inv_tenant__2244b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='billing_inv_invoice_355b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='billing_inv_date_9e0933_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant'], name='billing_rec_tenant__db0234_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice'], name='billing_rec_invoice_1a519f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['date'], name='billing_rec_date_0da193_idx'),
        ),
        migrations.AddField(
            model_name='latepenaltyconfig',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Apply to all tenants in this property (null = system default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_configs', to='masterfile.property'),
        ),
        migrations.AddField(
            model_name='latepenaltyconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Override for a specific tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_configs', to='masterfile.rentaltenant'),
        ),
        migrations.AddField(
            model_name='latepenaltyexclusion',
            name='excluded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='latepenaltyexclusion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_exclusions', to='masterfile.rentaltenant'),
        ),
        migrations.AddIndex(
            model_name='latepenaltyconfig',
            index=models.Index(fields=['tenant', 'is_enabled'], name='billing_lat_tenant__b40f68_idx'),
        ),
        migrations.AddIndex(
            model_name='latepenaltyconfig',
            index=models.Index(fields=['property', 'is_enabled'], name='billing_lat_propert_098a32_idx'),
        ),
        migrations.AddIndex(
            model_name='latepenaltyexclusion',
            index=models.Index(fields=['tenant'], name='billing_lat_tenant__304912_idx'),
        ),
    ]
