# Generated by Django 5.0.14 on 2026-02-19 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_search_filter_indexes'),
        ('billing', '0005_add_receipt_indexes'),
        ('masterfile', '0007_add_search_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='billing_exp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_status_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='billing_exp_expense_c27401_idx',
            old_name='billing_exp_type_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='billing_exp_date_31b117_idx',
            old_name='billing_exp_date_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='billing_exp_payee_t_113312_idx',
            old_name='billing_exp_payee_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_currenc_96f355_idx',
            old_name='billing_inv_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='billing_rec_payment_b8fb97_idx',
            old_name='billing_rct_method_idx',
        ),
        migrations.RenameIndex(
            model_name='receipt',
            new_name='billing_rec_currenc_bfd102_idx',
            old_name='billing_rct_currency_idx',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'date'], name='billing_exp_status_fdd8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['currency'], name='billing_exp_currenc_fe3a02_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['property'], name='billing_inv_propert_2ac64d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'balance'], name='billing_inv_status_76bdbd_idx'),
        ),
    ]
