# Generated by Django 5.0.14 on 2026-02-21 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_search_filter_indexes'),
        ('billing', '0007_alter_expense_managers_alter_invoice_managers_and_more'),
        ('masterfile', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'date'], name='billing_inv_tenant__2dda68_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['unit', 'date'], name='billing_inv_unit_id_4080dd_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'date'], name='billing_rec_tenant__fff5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['date', 'invoice'], name='billing_rec_date_cc2c08_idx'),
        ),
    ]
