# Generated by Django 5.0.14 on 2026-02-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_incometype_is_system_incometype_management_type'),
        ('billing', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='income_type',
            field=models.ForeignKey(blank=True, help_text='Income category this expense is matched against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.incometype'),
        ),
    ]
