# Generated by Django 5.0.14 on 2026-05-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_expensecategory_default_description_and_more'),
        ('billing', '0009_expense_expense_category_expense_income_type'),
        ('masterfile', '0012_make_lease_unit_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Source of funds — drives currency and cash GL account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='landlord',
            field=models.ForeignKey(blank=True, help_text='Landlord whose trust sub-account funds this expense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='masterfile.landlord'),
        ),
    ]
