# Generated by Django 5.0.14 on 2026-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_expense_bank_account_expense_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sub_account_category',
            field=models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit'), ('general', 'General')], default='rent', help_text='Landlord sub-account this payment is credited to', max_length=20),
        ),
    ]
