# Generated by Django 5.0.14 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_receipt_sub_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_kind',
            field=models.CharField(choices=[('cash', 'Cash'), ('non_cash', 'Non-Cash')], default='cash', help_text='Cash leaves the bank; Non-Cash is an accrual / depreciation', max_length=20),
        ),
    ]
