# Generated by Django 5.0.14 on 2026-05-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_expense_sub_account_category'),
        ('masterfile', '0013_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Vendor / service provider paid (e.g. City of Harare)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='masterfile.supplier'),
        ),
    ]
