# Generated by Django 5.0.14 on 2026-06-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_expense_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='clears_payable',
            field=models.BooleanField(default=False, help_text='Settles an outstanding supplier payable (Dr Accounts Payable, Cr Cash)'),
        ),
    ]
