# Generated by Django 5.0.14 on 2026-07-16 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_expense_clears_payable'),
        ('masterfile', '0015_supplier_tin_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(help_text='The manually chosen date to send on')),
                ('send_all', models.BooleanField(default=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, help_text='Optional extra text; the outstanding balance details are always included')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('excluded_properties', models.ManyToManyField(blank=True, help_text='Tenants of these properties are never sent reminders', related_name='excluded_payment_reminders', to='masterfile.property')),
                ('properties', models.ManyToManyField(blank=True, help_text='Only tenants of these properties (when not send_all)', related_name='payment_reminders', to='masterfile.property')),
                ('tenants', models.ManyToManyField(blank=True, help_text='Only these tenants/account holders (when not send_all)', related_name='payment_reminders', to='masterfile.rentaltenant')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
                'ordering': ['-send_date', '-created_at'],
            },
        ),
    ]
