# Generated by Django 5.0.14 on 2026-08-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_paymentreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latepenaltyconfig',
            name='penalty_type',
            field=models.CharField(choices=[('percentage', 'Percentage of Invoice'), ('flat_fee', 'Flat Fee'), ('both', 'Percentage + Flat Fee'), ('minimums', 'Minimums Method (% of min[Monthly Charge, Closing Balance])')], default='percentage', max_length=20),
        ),
    ]
