# Generated by Django 5.0.14 on 2026-08-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_latepenaltyconfig_penalty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='billing.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reversed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
