# Generated by Django 5.1.7 on 2026-01-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('demo_expired', 'Demo Expired'), ('suspended', 'Suspended')], default='active', help_text='Current account status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo_user',
            field=models.BooleanField(default=False, help_text='Whether this is a demo user'),
        ),
    ]
