# Generated by Django 5.0.14 on 2026-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_account_status_user_is_demo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_schema',
            field=models.CharField(blank=True, default='', help_text='Schema name of the tenant this user belongs to', max_length=63),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='tenant_schema',
            field=models.CharField(blank=True, default='', help_text='Schema name of the tenant this invitation belongs to', max_length=63),
        ),
    ]
