# Generated by Django 5.0.14 on 2026-02-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='tenant_schema',
            field=models.CharField(blank=True, default='', help_text='Schema name of the tenant this reset token belongs to', max_length=63),
        ),
    ]
