# Generated by Django 5.0.14 on 2026-02-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken_tenant_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('clerk', 'Clerk'), ('tenant_portal', 'Tenant Portal'), ('landlord_portal', 'Landlord Portal')], default='clerk', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('clerk', 'Clerk'), ('tenant_portal', 'Tenant Portal'), ('landlord_portal', 'Landlord Portal')], default='clerk', max_length=20),
        ),
    ]
