# Generated by Django 5.0.14 on 2026-08-23 15:31

from django.db import migrations, models

# Legacy role -> (user_type, permission_role). Kept inline (not imported from
# apps.accounts.capabilities) so this migration stays stable if the registry
# is later edited.
_LEGACY_ROLE_TO_TYPE = {
    'super_admin': ('super_admin', 'super_admin_full'),
    'admin': ('admin', 'admin_default'),
    'accountant': ('accounts_officer', 'accounts_officer_default'),
    'clerk': ('clerk', 'clerk_default'),
    'tenant_portal': ('tenant', 'tenant_portal_only'),
    'landlord_portal': ('account_holder', 'account_holder_portal_only'),
}


def backfill_user_type(apps, schema_editor):
    """Derive user_type + permission_role from each user's existing role."""
    User = apps.get_model('accounts', 'User')
    for role, (utype, prole) in _LEGACY_ROLE_TO_TYPE.items():
        User.objects.filter(role=role).update(
            user_type=utype, permission_role=prole
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role_alter_userinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Capability codes used only when permission_role == 'custom'."),
        ),
        migrations.AddField(
            model_name='user',
            name='permission_role',
            field=models.CharField(choices=[('super_admin_full', 'Super Admin (Full Platform)'), ('admin_default', 'Admin Default'), ('accounts_officer_default', 'Accounts Officer Default'), ('clerk_default', 'Clerk Default'), ('cashier_default', 'Cashier Default'), ('portfolio_manager_default', 'Portfolio Manager Default'), ('tenant_portal_only', 'Tenant Portal Only'), ('account_holder_portal_only', 'Account Holder Portal Only'), ('custom', 'Custom / Internal Role')], default='clerk_default', help_text="Named capability set. 'custom' uses custom_capabilities.", max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accounts_officer', 'Accounts Officer'), ('clerk', 'Clerk'), ('cashier', 'Cashier'), ('portfolio_manager', 'Portfolio Manager'), ('tenant', 'Tenant'), ('account_holder', 'Account Holder')], default='clerk', help_text="The user's identity/category (separate from their permissions).", max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('clerk', 'Clerk'), ('tenant_portal', 'Tenant Portal'), ('landlord_portal', 'Landlord Portal')], default='clerk', help_text='Legacy role — auto-mirrored from user_type. Prefer user_type/permission_role.', max_length=20),
        ),
        migrations.RunPython(backfill_user_type, noop_reverse),
    ]
