# Generated by Django 5.0.14 on 2026-08-23 16:19

from django.db import migrations, models

_LEGACY_ROLE_TO_TYPE = {
    'super_admin': 'super_admin',
    'admin': 'admin',
    'accountant': 'accounts_officer',
    'clerk': 'clerk',
    'tenant_portal': 'tenant',
    'landlord_portal': 'account_holder',
}


def backfill_invitation_type(apps, schema_editor):
    """Derive user_type from the existing role on pending invitations so the
    new default ('clerk') doesn't silently downgrade them."""
    UserInvitation = apps.get_model('accounts', 'UserInvitation')
    for role, utype in _LEGACY_ROLE_TO_TYPE.items():
        UserInvitation.objects.filter(role=role).update(user_type=utype)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_custom_capabilities_user_permission_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accounts_officer', 'Accounts Officer'), ('clerk', 'Clerk'), ('cashier', 'Cashier'), ('portfolio_manager', 'Portfolio Manager'), ('tenant', 'Tenant'), ('account_holder', 'Account Holder')], default='clerk', help_text='User type the invitee will be created as on acceptance.', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('clerk', 'Clerk'), ('tenant_portal', 'Tenant Portal'), ('landlord_portal', 'Landlord Portal')], default='clerk', help_text='Legacy role mirror — derived from user_type.', max_length=20),
        ),
        migrations.RunPython(backfill_invitation_type, noop_reverse),
    ]
