# Generated by Django 5.1.7 on 2026-01-16 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('demo_expired', 'Demo Expired'), ('suspended', 'Suspended')], default='pending', help_text='Current account status', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='demo_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the demo expires', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this is a demo account'),
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of the company admin', max_length=254)),
                ('company_name', models.CharField(help_text='Name of the company', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('invitation_type', models.CharField(choices=[('full', 'Full Account'), ('demo', 'Demo Account')], default='full', help_text='Type of account to create', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional welcome message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_tenant', models.ForeignKey(blank=True, help_text='The tenant created from this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='tenants.client')),
                ('invited_by', models.ForeignKey(help_text='Super admin who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Invitation',
                'verbose_name_plural': 'Tenant Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
