# Generated by Django 4.2.27 on 2026-01-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_account_status_client_demo_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=30)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=255)),
                ('admin_first_name', models.CharField(max_length=150)),
                ('admin_last_name', models.CharField(max_length=150)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('login_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Demo Signup Request',
                'verbose_name_plural': 'Demo Signup Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
