# Generated by Django 4.2.27 on 2026-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_demo_signup_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, help_text='When set, company will be permanently deleted after this time (24h grace period)', null=True),
        ),
    ]
