# Generated by Django 5.0.14 on 2026-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_scheduled_deletion_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_footer',
            field=models.TextField(default='Thank you for your business!'),
        ),
        migrations.AddField(
            model_name='client',
            name='invoice_prefix',
            field=models.CharField(default='INV-', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_currency',
            field=models.CharField(default='ZiG', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='show_logo',
            field=models.BooleanField(default=True),
        ),
    ]
