# Generated by Django 4.2.27 on 2026-01-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='lease_type',
            field=models.CharField(choices=[('rental', 'Rental Lease'), ('levy', 'Levy Account')], default='rental', max_length=20),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='masterfile.property'),
        ),
        migrations.AddField(
            model_name='rentaltenant',
            name='account_type',
            field=models.CharField(choices=[('rental', 'Rental Tenant'), ('levy', 'Levy Account Holder'), ('both', 'Both (Rental & Levy)')], default='rental', help_text='Rental tenant or levy account holder', max_length=20),
        ),
    ]
