# Generated by Django 5.0.14 on 2026-01-28 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0002_leaseagreement_lease_type_leaseagreement_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaltenant',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit allocated to this tenant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenants', to='masterfile.unit'),
        ),
        migrations.AlterField(
            model_name='leaseagreement',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional deposit amount', max_digits=18, null=True),
        ),
    ]
