# Generated by Django 5.0.14 on 2026-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0003_add_unit_to_tenant_relax_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit_definition',
            field=models.CharField(
                blank=True,
                help_text='Define unit range: "1-17" or "A1-A20; B1-B15" etc.',
                max_length=500
            ),
        ),
    ]
