# Generated by Django 5.0.14 on 2026-02-15 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0004_property_unit_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Manager',
                'verbose_name_plural': 'Property Managers',
                'ordering': ['-is_primary', 'assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['status'], name='masterfile__status_d78ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['tenant', 'status'], name='masterfile__tenant__419bad_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['unit', 'status'], name='masterfile__unit_id_20d653_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['start_date', 'end_date'], name='masterfile__start_d_f8bdf1_idx'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='masterfile.property'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['super_admin', 'admin', 'accountant', 'clerk']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertymanager',
            unique_together={('user', 'property')},
        ),
    ]
