# Generated by Django 5.0.14 on 2026-02-19 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0006_add_unit_is_occupied_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unit',
            name='mf_unit_occupied_idx',
        ),
        migrations.RenameIndex(
            model_name='unit',
            new_name='masterfile__propert_df43d1_idx',
            old_name='mf_unit_prop_occ_idx',
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['name'], name='masterfile__name_e57bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['is_active'], name='masterfile__is_acti_e0a10d_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['landlord_type', 'is_active'], name='masterfile__landlor_5c945e_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['created_at'], name='masterfile__created_7daf3a_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['email'], name='masterfile__email_3ca9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='masterfile__name_a70861_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord', 'is_active'], name='masterfile__landlor_a5da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'is_active'], name='masterfile__propert_22e63d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='masterfile__city_f5695c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='masterfile__created_b5a8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['name'], name='masterfile__name_6ce9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['is_active'], name='masterfile__is_acti_0a3b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['tenant_type', 'is_active'], name='masterfile__tenant__677036_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['account_type'], name='masterfile__account_f90dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['email'], name='masterfile__email_307d31_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltenant',
            index=models.Index(fields=['created_at'], name='masterfile__created_2afb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_occupied', 'is_active'], name='masterfile__is_occu_c7adcf_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type'], name='masterfile__unit_ty_ac3418_idx'),
        ),
    ]
