# Generated by Django 5.0.14 on 2026-02-21 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0008_alter_landlord_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['status', 'end_date'], name='masterfile__status_765923_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['-created_at'], name='masterfile__created_c40665_idx'),
        ),
    ]
