# Generated by Django 5.0.14 on 2026-02-26 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0009_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='management_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('levy', 'Levy')], default='rental', help_text='Determines income structures, unit creation, and vacancy reporting', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['management_type', 'is_active'], name='masterfile__managem_02b658_idx'),
        ),
    ]
