# Generated by Django 5.0.14 on 2026-02-28 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0010_property_management_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='portal_user',
            field=models.OneToOneField(blank=True, help_text='User account for landlord self-service portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='last_escalation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='original_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original rent before escalations', max_digits=18, null=True),
        ),
    ]
