# Generated by Django 5.0.14 on 2026-03-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0011_landlord_portal_user_leaseagreement_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseagreement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='masterfile.unit'),
        ),
    ]
