# Generated by Django 5.0.14 on 2026-05-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_expensecategory_default_description_and_more'),
        ('masterfile', '0013_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyIncomeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g. 10.00 = 10%)', max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('income_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_commission_overrides', to='accounting.incometype')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_commissions', to='masterfile.property')),
            ],
            options={
                'verbose_name': 'Property income commission',
                'verbose_name_plural': 'Property income commissions',
                'ordering': ['property__name', 'income_type__name'],
                'indexes': [models.Index(fields=['property', 'income_type'], name='masterfile__propert_ad51cf_idx')],
                'unique_together': {('property', 'income_type')},
            },
        ),
    ]
