# Generated by Django 5.0.14 on 2026-07-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0014_property_income_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
