# Generated by Django 5.0.14 on 2026-07-19 12:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0015_supplier_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='masterfile.leaseagreement')),
            ],
            options={
                'verbose_name': 'Lease Charge',
                'verbose_name_plural': 'Lease Charges',
                'ordering': ['charge_type'],
                'unique_together': {('lease', 'charge_type')},
            },
        ),
    ]
