# Generated by Django 5.0.14 on 2026-07-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0016_leasecharge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leasecharge',
            unique_together={('lease', 'charge_type', 'currency')},
        ),
    ]
