# Generated by Django 5.0.14 on 2026-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0017_payer_side_and_ccy_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
