# Generated by Django 5.0.14 on 2026-08-10 16:36

from django.db import migrations, models


def both_to_rental(apps, schema_editor):
    """Retire the prohibited 'both' payer type — collapse any such account to
    Rental (they were already TN-coded as rentals). Payer type is now a
    mutually-exclusive Rental-XOR-Levy attribute."""
    RentalTenant = apps.get_model('masterfile', 'RentalTenant')
    RentalTenant._base_manager.filter(account_type='both').update(account_type='rental')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0018_currency_conversions'),
    ]

    operations = [
        migrations.RunPython(both_to_rental, noop),
        migrations.AlterField(
            model_name='rentaltenant',
            name='account_type',
            field=models.CharField(choices=[('rental', 'Rental Tenant'), ('levy', 'Levy Account Holder')], default='rental', help_text='Rental tenant or levy account holder', max_length=20),
        ),
    ]
