# Generated by Django 5.0.14 on 2026-08-12 06:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterfile', '0019_alter_rentaltenant_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('levy', 'Levy'), ('special_levy', 'Special Levy'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('rates', 'Rates'), ('vat', 'VAT'), ('deposit', 'Deposit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('once', 'Once')], default='monthly', max_length=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Last day this rate applies (blank = open-ended)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_configs', to='masterfile.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property billing configuration',
                'verbose_name_plural': 'Property billing configurations',
                'ordering': ['property__name', 'category', '-effective_from'],
                'indexes': [models.Index(fields=['property', 'category', 'is_active'], name='masterfile__propert_aa1fa1_idx'), models.Index(fields=['effective_from'], name='masterfile__effecti_c50403_idx')],
            },
        ),
    ]
