/**
 * Print utility functions for Parameter Real Estate Accounting
 */

export interface PrintOptions {
  title?: string
  subtitle?: string
  orientation?: 'portrait' | 'landscape'
}

/**
 * Print the content of a specific element
 */
export function printElement(elementId: string, options: PrintOptions = {}) {
  const element = document.getElementById(elementId)
  if (!element) {
    console.error(`Element with ID "${elementId}" not found`)
    return
  }

  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    console.error('Unable to open print window')
    return
  }

  const { title = 'Parameter Report', subtitle = '', orientation = 'portrait' } = options

  const content = element.innerHTML

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @page {
          size: A4 ${orientation};
          margin: 1.5cm;
        }

        * {
          box-sizing: border-box;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
          line-height: 1.6;
          color: #1a1a1a;
          padding: 20px;
          margin: 0;
        }

        .print-header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #e5e7eb;
        }

        .print-header h1 {
          font-size: 24px;
          font-weight: 700;
          margin: 0 0 5px 0;
          color: #111827;
        }

        .print-header p {
          font-size: 14px;
          color: #6b7280;
          margin: 0;
        }

        .print-meta {
          display: flex;
          justify-content: space-between;
          font-size: 12px;
          color: #6b7280;
          margin-bottom: 20px;
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
        }

        th, td {
          padding: 12px;
          text-align: left;
          border-bottom: 1px solid #e5e7eb;
        }

        th {
          background-color: #f9fafb;
          font-weight: 600;
          font-size: 12px;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          color: #374151;
        }

        td {
          font-size: 14px;
        }

        tr:nth-child(even) {
          background-color: #f9fafb;
        }

        .amount, .currency {
          text-align: right;
          font-variant-numeric: tabular-nums;
        }

        .total-row {
          font-weight: 700;
          background-color: #f3f4f6 !important;
        }

        .debit {
          color: #059669;
        }

        .credit {
          color: #dc2626;
        }

        .print-footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          font-size: 11px;
          color: #9ca3af;
          text-align: center;
        }

        @media print {
          body {
            padding: 0;
          }

          .no-print {
            display: none !important;
          }
        }
      </style>
    </head>
    <body>
      <div class="print-header">
        <h1>${title}</h1>
        ${subtitle ? `<p>${subtitle}</p>` : ''}
      </div>

      <div class="print-meta">
        <span>Generated: ${new Date().toLocaleString()}</span>
        <span>Parameter.co.zw</span>
      </div>

      ${content}

      <div class="print-footer">
        Generated by Parameter Real Estate Accounting System &bull; ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `)

  printWindow.document.close()

  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.focus()
    printWindow.print()
    printWindow.close()
  }
}

/**
 * Generate a printable table from data
 */
export function generatePrintableTable<T extends Record<string, any>>(
  data: T[],
  columns: { key: keyof T; label: string; align?: 'left' | 'right' | 'center' }[],
  options: PrintOptions = {}
) {
  const { title = 'Report', subtitle = '' } = options

  const tableRows = data.map(row => {
    const cells = columns.map(col => {
      const value = row[col.key]
      const align = col.align || 'left'
      return `<td style="text-align: ${align}">${value ?? '-'}</td>`
    }).join('')
    return `<tr>${cells}</tr>`
  }).join('')

  const tableHeaders = columns.map(col => {
    const align = col.align || 'left'
    return `<th style="text-align: ${align}">${col.label}</th>`
  }).join('')

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @page { size: A4; margin: 1.5cm; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          padding: 20px;
          color: #1a1a1a;
        }
        h1 { font-size: 24px; margin: 0 0 5px 0; }
        .subtitle { color: #6b7280; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
        th { background: #f9fafb; text-transform: uppercase; font-size: 12px; letter-spacing: 0.05em; }
        tr:nth-child(even) { background: #f9fafb; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      ${subtitle ? `<p class="subtitle">${subtitle}</p>` : ''}
      <table>
        <thead><tr>${tableHeaders}</tr></thead>
        <tbody>${tableRows}</tbody>
      </table>
      <div class="footer">Generated by Parameter Real Estate Accounting System &bull; ${new Date().toLocaleDateString()}</div>
    </body>
    </html>
  `)

  printWindow.document.close()
  printWindow.onload = () => {
    printWindow.focus()
    printWindow.print()
    printWindow.close()
  }
}

/**
 * Print current window
 */
export function printPage() {
  window.print()
}
