# Generated by Django 5.0.14 on 2026-09-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='import_type',
            field=models.CharField(choices=[('landlords', 'Landlords'), ('properties', 'Properties'), ('tenants', 'Tenants'), ('account_holders', 'Account Holders'), ('leases', 'Leases'), ('invoices', 'Invoices'), ('receipts', 'Receipts'), ('combined', 'Combined (Multi-sheet)')], max_length=20),
        ),
    ]
